### ISSUE TITLE
Améliorer la doc d'installation

### ISSUE THREAD

**Issue by blackheaven** [ThomasBracher/crafters#1]
Pour l'instant je suis coincé au webpack : 

```
$ webpack
Hash: 87a3f4b79e2ea38f3a24
Version: webpack 3.8.1
Time: 2079ms
          Asset      Size  Chunks             Chunk Names
      js/app.js   1.03 kB       0  [emitted]  app
    css/app.css    230 kB       0  [emitted]  app
css/app.css.map  88 bytes       0  [emitted]  app
   [0] multi ./js/src/App.js ./css/app.scss 40 bytes {0} [built]
   [1] ./js/src/App.js 89 bytes {0} [built]
   [2] ./js/src/Main.purs 457 bytes {0} [built] [failed] [1 error]
   [3] ./css/app.scss 41 bytes {0} [built]

ERROR in ./js/src/Main.purs
Module build failed: Error: compilation failed
    at ChildProcess.<anonymous> (/home/black/programmation/elixir/crafters/front/node_modules/purs-loader/lib/compile.js:53:18)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:559:12)
 @ ./js/src/App.js 3:0-22
 @ multi ./js/src/App.js ./css/app.scss

ERROR in [31m[1/127 ModuleNotFound][0m js/src/Activity.purs[2m:[0m3[2m:[0m1

  [2m3  [0mimport Data.Argonaut.Core (Json, fromString)
     [31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m
  
  Module Data.Argonaut.Core was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[31m[2/127 ModuleNotFound][0m js/src/Activity.purs[2m:[0m4[2m:[0m1
```

**Comment by sadraskol** [comment]
Je n'ai pas préciser dans le readme : dans le dossier `front`, il faut lancer `npm install` et `bower install`. Je pense qu'il te manque le dernier.

**Comment by blackheaven** [comment]
`bower install` ne fait rien et `npm install` me dit que tout est bon.

**Comment by sadraskol** [comment]
Bower ne fait rien ? tu es sûr d'être dans le dossier `front` ?

ps: j'ai mis à jour le readme pour être plus explicite sur les prérequis, j'ai peut être oublié des choses.

**Comment by sadraskol** [comment]
Dans le pire des cas, tu peux utiliser le docker-compose avec le dockerfile pour tester. Bien que ça ne soit pas utile pour développer en local, ça permet peut être de comprendre ce qui cloche en local. Je clos le fil de conversation du coup
